version: '3.8'

services:
  db:
    image: postgres:13
    container_name: toll_db
    restart: always
    environment:
      POSTGRES_DB: toll_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: toll_backend
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  db_data:
